apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-env-deployment
  labels:
    app: dev-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-env
  template:
    metadata:
      labels:
        app: dev-env
    spec:
      containers:
      - name: dev-env
        image: jaksa76/dev-env
        imagePullPolicy: Always
        ports:
        - containerPort: 22
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dev-env
  labels:
    app: dev-env
spec:
  type: LoadBalancer
  ports:
  - port: 22
    name: ssh
    protocol: TCP
  - port: 8080
    name: http
    protocol: TCP
  selector:
    app: dev-env
